modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/raws/mattercraft/issues"

[[mods]]
  modId="mattercraft"
  version="0.1"
  displayName="Mattercraft"
  displayURL="https://github.com/raws/mattercraft"
  authors="Ross Paffett"
  description='''
  Bridges chat messages between a Minecraft server and Matterbridge.
  '''
  displayTest="IGNORE_ALL_VERSION"